# install.ps1 — Windows installer for arboractive.
# Creates a .venv next to this script, installs the package editable, and
# writes a clickable arboractive-gui.bat launcher in the repo root.
#
# WeasyPrint requires the GTK runtime on Windows. If PDF export fails with a
# "cannot load library" error, install GTK from
# https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases
# and reopen the shell so the new PATH is picked up.

$ErrorActionPreference = "Stop"

$RepoDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$VenvDir = Join-Path $RepoDir ".venv"

# Prefer the `py` launcher (ships with python.org installer) since it lets us
# explicitly pin Python 3. Fall back to bare `python` if `py` isn't present.
function New-Venv {
    param([string]$Target)
    if (Get-Command py -ErrorAction SilentlyContinue) {
        & py -3 -m venv $Target
    } elseif (Get-Command python -ErrorAction SilentlyContinue) {
        & python -m venv $Target
    } else {
        throw "No Python interpreter found. Install Python 3.11+ from python.org."
    }
}

if (-not (Test-Path $VenvDir)) {
    Write-Host "Creating venv at $VenvDir"
    New-Venv $VenvDir
}

$VenvPython = Join-Path $VenvDir "Scripts\python.exe"
& $VenvPython -m pip install --upgrade pip
& $VenvPython -m pip install -e $RepoDir

$GuiExe = Join-Path $VenvDir "Scripts\arboractive-gui.exe"
$Launcher = Join-Path $RepoDir "arboractive-gui.bat"

# `start "" /B` so the cmd window closes immediately after launching the GUI;
# without it the console sticks around behind the Tk window.
@"
@echo off
REM Auto-generated by install.ps1. Launches the ArborActive GUI in its venv.
start "" /B "$GuiExe" %*
"@ | Set-Content -Encoding ASCII -Path $Launcher

Write-Host ""
Write-Host "Installed. Run the GUI by double-clicking:"
Write-Host "  $Launcher"
