#!/usr/bin/env bash
# Create .venv, install arboractive into it, and drop a `arboractive-gui`
# launcher in the repo root that activates the venv and starts the GUI.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$REPO_DIR/.venv"
PY="${PYTHON:-python3}"

if [ ! -d "$VENV_DIR" ]; then
  echo "Creating venv at $VENV_DIR"
  "$PY" -m venv "$VENV_DIR"
fi

# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"

pip install --upgrade pip
pip install -e "$REPO_DIR"

LAUNCHER="$REPO_DIR/arboractive-gui"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by install.sh. Launches the ArborActive GUI in its venv.
exec "$VENV_DIR/bin/arboractive-gui" "\$@"
EOF
chmod +x "$LAUNCHER"

echo
echo "Installed. Run the GUI with:"
echo "  $LAUNCHER"
